# Generated by GPT4o on 6-22-24 for refactoring package structure since IntelliJ became incompetent

import os
import shutil

# Define the old and new package structures
old_package = 'cyderutils'
new_package = 'com.github.natche.cyderutils'
main_src_dir = 'src/main/java'
test_src_dir = 'src/test/java'

def replace_in_file(file_path, old_pkg, new_pkg):
    with open(file_path, 'r') as file:
        content = file.read()
    content = content.replace(f'package {old_pkg}', f'package {new_pkg}')
    content = content.replace(f'import {old_pkg}', f'import {new_pkg}')
    content = content.replace(f'import static {old_pkg}', f'import static {new_pkg}')
    with open(file_path, 'w') as file:
        file.write(content)

def update_imports_and_package_declarations(base_dir, old_pkg, new_pkg):
    for root, dirs, files in os.walk(base_dir):
        for file in files:
            if file.endswith('.java'):
                file_path = os.path.join(root, file)
                replace_in_file(file_path, old_pkg, new_pkg)

def move_package(src_dir, old_pkg, new_pkg):
    old_path = os.path.join(src_dir, old_pkg.replace('.', '/'))
    new_path = os.path.join(src_dir, new_pkg.replace('.', '/'))

    if not os.path.exists(new_path):
        os.makedirs(new_path)

    for root, dirs, files in os.walk(old_path):
        for file in files:
            old_file_path = os.path.join(root, file)
            relative_path = os.path.relpath(old_file_path, old_path)
            new_file_path = os.path.join(new_path, relative_path)
            new_file_dir = os.path.dirname(new_file_path)
            if not os.path.exists(new_file_dir):
                os.makedirs(new_file_dir)
            shutil.move(old_file_path, new_file_path)

    # Remove old package directory
    shutil.rmtree(old_path)

# Update imports and package declarations in src/main/java
update_imports_and_package_declarations(main_src_dir, old_package, new_package)
# Move the package in src/main/java
move_package(main_src_dir, old_package, new_package)

# Update imports and package declarations in src/test/java
update_imports_and_package_declarations(test_src_dir, old_package, new_package)
# Move the package in src/test/java
move_package(test_src_dir, old_package, new_package)

print("Refactoring complete.")
