name: Verify Scream installation file

on:
  push:
  workflow_dispatch:

jobs:
  verify:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies on Windows
        run: |
          choco install openjdk python
          python -m pip install --upgrade pip
          pip install mutagen

      - name: Download and install Scream virtual audio card
        run: |
          # Set the system date back to a valid time for the certificate
          $currentDate = Get-Date
          $newDate = Get-Date "2023-07-04 12:00:00"
          Set-Date $newDate

          # Download Scream
          $screamUrl = "https://github.com/duncanthrax/scream/releases/download/4.0/Scream4.0.zip"
          Invoke-WebRequest -Uri $screamUrl -OutFile "scream.zip"
          Expand-Archive -Path "scream.zip" -DestinationPath "Scream"

          # Verify extraction
          Get-ChildItem -Path "Scream"
          Get-ChildItem -Path "Scream\Install"

          # Ensure correct path
          $installPath = Join-Path $pwd "Scream\Install\install-x64.bat"
          Write-Host "Install Path: $installPath"
          if (Test-Path $installPath) {
              Write-Host "Install file found"

              # Install the driver with timeout and logging
              $process = Start-Process -FilePath $installPath -ArgumentList "/S" -NoNewWindow -Wait -PassThru
              $process.WaitForExit(600000)  # Timeout after 10 minutes (600,000 milliseconds)

              if ($process.HasExited) {
                  Write-Host "Driver installation completed with exit code $($process.ExitCode)"
              } else {
                  Write-Host "Driver installation timed out"
                  Stop-Process -Id $process.Id
              }

              # Revert the system date back to current
              Set-Date $currentDate

              # Verify the driver installation
              Write-Host "Verifying driver installation"
              Get-PnpDevice | Where-Object { $_.FriendlyName -like "*Scream*" } | Format-List
          } else {
              Write-Host "Install file NOT found"
          }
        shell: powershell

      - name: Echo Verification Result
        run: echo Driver installation verification completed.
