name: Java Audio Setup Check

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-audio:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.6'
          distribution: 'temurin'

      - name: Install PulseAudio
        run: |
          sudo apt-get update
          sudo apt-get install -y pulseaudio
          pulseaudio --check || pulseaudio --start
          pactl load-module module-null-sink sink_name=default

      - name: Create and run Java audio test
        run: |
          echo 'import javax.sound.sampled.AudioSystem;
          import javax.sound.sampled.Clip;

          public class AudioTest {
              public static void main(String[] args) {
                  try {
                      Clip clip = AudioSystem.getClip();
                      System.out.println("Audio system initialized successfully.");
                  } catch (Exception e) {
                      e.printStackTrace();
                  }
              }
          }' > AudioTest.java
          javac AudioTest.java
          java AudioTest
